### ISSUE TITLE
Installing pytorch as per ShARC instructions can fail (invalid block type)

### ISSUE THREAD

**Issue by willfurnass** [rcgsheffield/sheffield_hpc#1050]
I think this was due to the version of pip being old:

```
$ pip install torch torchvision
Collecting torch
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/62/01/457b49d790b6c4b9720e6f9dbbb617692f6ce8afdaadf425c055c41a7416/torch-1.5.1-cp36-cp36m-manylinux1_x86_64.whl (753.2MB)
    100% |████████████████████████████████| 753.2MB 1.8kB/s
Collecting torchvision
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/9a/f1/535a407b4a265adf2dd7c2c2458217e37c5fe83ec97234e66c564592a9a0/torchvision-0.6.1-cp36-cp36m-manylinux1_x86_64.whl (6.6MB)
    100% |████████████████████████████████| 6.6MB 199kB/s
Collecting future (from torch)
  Cache entry deserialization failed, entry ignored
  Downloading https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz (829kB)
    100% |████████████████████████████████| 829kB 1.4MB/s
Collecting numpy (from torch)
Collecting numpy (from torch)
Exception:
Traceback (most recent call last):
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 617, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 617, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 177, in resolve_redirects
    **adapter_kwargs
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 37, in send
    cached_response = self.controller.cached_request(request)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/cachecontrol/controller.py", line 111, in cached_request
    resp = self.serializer.loads(request, cache_data)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/cachecontrol/serialize.py", line 114, in loads
    return getattr(self, "_loads_v{0}".format(ver))(request, data)
  File "/data/te1st/.conda-sharc/envs/pytorch/lib/python3.6/site-packages/pip/_vendor/cachecontrol/serialize.py", line 176, in _loads_v2
    cached = json.loads(zlib.decompress(data).decode("utf8"))
zlib.error: Error -3 while decompressing data: invalid block type
You are using pip version 9.0.1, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

And the suggestion of `pip install --upgrade pip` did help.   

@twinkarma Have you encountered this issue before?

Ways of addressing this:
1. if users want to use pip in conda environments created from the central conda install on ShARC then can update docs to recommend they upgrade pip in new conda envs before using it
2. upgrade the central conda install on ShARC (just pip or the whole root conda env)

**Comment by twinkarma** [comment]
I've had problems where you run out of memory as installing pytorch takes more than 2GB but this looks like pip version problem then.

Can we just update pip for everyone by default?

**Comment by willfurnass** [comment]
Possibly.  I need to check if there have been behavioural changes between pip 9.0.1 & 20.1.1 that might discourage us from doing this.

**Comment by twinkarma** [comment]
Actually it'll probably be less work to just tell users to upgrade pip case-by-case, it's only been PyTorch so far right?
