### ISSUE TITLE
Conda not able to install CMake on ShARC (and a few other packages), "permission denied" error

### ISSUE THREAD

**Issue by twinkarma** [rcgsheffield/sheffield_hpc#530]
I'm using Anaconda 3 and the environment is python 3.5

This is what I've been getting when trying to install CMake:

```
$ conda install cmake

Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/ac1tk/.conda/envs/theano:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.6                |                3          83 KB

The following NEW packages will be INSTALLED:

    bzip2:   1.0.6-3  (copy)
    cmake:   3.6.3-0 
    curl:    7.49.0-1 (soft-link)
    expat:   2.1.0-0  (soft-link)
    ncurses: 5.9-10  

Proceed ([y]/n)?  

Fetching packages ...
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
An unexpected error has occurred.                                                                                                | ETA:  --:--:--   0.00  B/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.6
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /usr/local/packages/apps/conda  (read only)
    default environment : /home/ac1tk/.conda/envs/theano
       envs directories : /home/ac1tk/.conda/envs
                          /usr/local/packages/apps/conda/envs
          package cache : /home/ac1tk/.conda/envs/.pkgs
                          /usr/local/packages/apps/conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /home/ac1tk/.conda/envs/theano/bin/conda install cmake`

    Traceback (most recent call last):
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/fetch.py", line 417, in download
        with open(pp, 'wb') as fo:
    PermissionError: [Errno 13] Permission denied: '/usr/local/packages/apps/conda/pkgs/bzip2-1.0.6-3.tar.bz2.part'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/usr/local/packages/apps/conda/pkgs/bzip2-1.0.6-3.tar.bz2.part' for writing ([Errno 13] Permission denied: '/usr/local/packages/apps/conda/pkgs/bzip2-1.0.6-3.tar.bz2.part').
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/usr/local/packages/apps/conda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/usr/local/packages/apps/conda/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/usr/local/packages/apps/conda/pkgs/bzip2-1.0.6-3.tar.bz2.part' for writing ([Errno 13] Permission denied: '/usr/local/packages/apps/conda/pkgs/bzip2-1.0.6-3.tar.bz2.part').

```

I've been getting this problem with a few other packages as well such as protobuf. Conda seems to want to download the tar/zip file to the admin-writable area causing a permission error, seems a strange behaviour for a supposedly self-contained environment to do.

**Comment by willfurnass** [comment]
I've encountered the same issue or something similar [before](https://groups.google.com/a/continuum.io/forum/#!topic/conda/fMqO2GNQqSU).  

Does the workaround proposed [here](https://github.com/conda/conda/issues/3448) by fellow-Sheffielder @IanSudbury  work for you?

We need to keep an eye on the conda changelog and **shouldn't close this issue** until we're happy that the documentation is sufficient w.r.t. this issue.

**Comment by karmauk** [comment]
Yes deleting the ~/.conda/env/.pkgs as suggested  works for me too. I do have multiple local environments that I have tried to install the same packages e.g. cmake on each of them and maybe that's what's causing an issue.

**Comment by karmauk** [comment]
I was also getting pip install error too that seems to have been solved by deleting the .pkgs folder. Error is below for reference.

```
$ pip install keras
Traceback (most recent call last):
  File "/home/ac1tk/.conda/envs/theano/bin/pip", line 4, in <module>
    import pip
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/_vendor/distlib/compat.py", line 66, in <module>
    from urllib.request import (urlopen, urlretrieve, Request, url2pathname,
ImportError: cannot import name 'HTTPSHandler'
(theano) [ac1tk@sharc-node126 bin]$ pip install openssl
Traceback (most recent call last):
  File "/home/ac1tk/.conda/envs/theano/bin/pip", line 4, in <module>
    import pip
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/home/ac1tk/.conda/envs/theano/lib/python3.5/site-packages/pip/_vendor/distlib/compat.py", line 66, in <module>
    from urllib.request import (urlopen, urlretrieve, Request, url2pathname,
ImportError: cannot import name 'HTTPSHandler'
```
