### ISSUE TITLE
Using Tensorflow with AVX2

### ISSUE THREAD

**Issue by drj11** [rcgsheffield/sheffield_hpc#906]
I followed the Tensorflow CPU installation instructions here: http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/tensorflow.html (short version: do a `pip install tensorflow` inside a conda environment).

If you use this tensorflow you get a INFO log entry saying:

```
2019-04-16 10:46:37.463574: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
```

The issue is: We should have a tensorflow compiled to use AVX2 and FMA.

In the comments I'll describe some antics.

**Comment by willfurnass** [comment]
@drj11 I may be able to build you Tensorflow with AVX2 + FMA support using EasyBuild (https://github.com/rcgsheffield/easybuild_testing) - let me know if that is of interest.

**Comment by drj11** [comment]
Yes please.

**Comment by drj11** [comment]
If you install tensorflow using conda: `conda install tensorflow` you get an older version of tensorflow but it has essentially the same error:

```
python -c 'import tensorflow;tensorflow.Session()'
2019-04-16 11:04:22.673331: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2019-04-16 11:04:22.673392: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2019-04-16 11:04:22.673435: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2019-04-16 11:04:22.673459: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2019-04-16 11:04:22.673586: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
```

**Comment by drj11** [comment]
Googling around leads to https://anaconda.org/intel/tensorflow-avx2, which suggests using the intel conda channel:

```
conda install -c intel tensorflow-avx2
```

```
Fetching package metadata ...........
Solving package specifications: 


PackageNotFoundError: Dependencies missing in current linux-64 channels: 
  - tensorflow-avx2 -> absl-py >=0.1.6
  - tensorflow-avx2 -> astor >=0.6.0
  - tensorflow-avx2 -> gast >=0.2.0
  - tensorflow-avx2 -> grpcio >=1.8.6
  - tensorflow-avx2 -> protobuf >=3.6.0
  - tensorflow-avx2 -> tensorboard >=1.10.0,<1.11.0

(and similarly for the other packages)
```

This appears to be a problem with the conda version (the above works using a recent conda on my laptop)

**Comment by willfurnass** [comment]
The centrally-installed conda on ShARC is old; if you encounter problems with it when using channels other than the default then try installing Miniconda3 in e.g. `/data/$USER`.

**Comment by drj11** [comment]
yes, you're right to suggest installing it in `/data/` because when I had installed it in `/user/` I ran out of space fairly quickly and then rage quit.

**Comment by willfurnass** [comment]
With the TensorFlow I've built using the 'foss-2018b' EasyBuild toolchain I don't get errors re no AVX2/FMA support as I optimised for Haswell; however:

$ module use '/usr/local/community/rse/EasyBuild/modules/all/all'
$ module unuse /usr/local/modulefiles 
$ module load TensorFlow/1.12.0-foss-2018b-Python-3.6.6
$ python -c 'import tensorflow;tensorflow.Session()'
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[19537,1],0] (PID 22718)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
2019-04-16 12:04:51.562257: I tensorflow/core/common_runtime/process_util.cc:69] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
```

Not sure what's triggered the MPI dependency...

**Comment by drj11** [comment]
Using a personal installation of miniconda3 in `/data/$USER` it still seems to not work (or, at best, be difficult to get working):

```
(tensorflow-avx2) ac1xdrj@sharc-node142:~$ python -c 'import tensorflow'
Traceback (most recent call last):
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/__init__.py", line 22, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libm.so.6: version `GLIBC_2.23' not found (required by /data/ac1xdrj/miniconda3/envs/tensorflow-avx2/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

`conda list` gives:
```
$ conda list
# packages in environment at /data/ac1xdrj/miniconda3/envs/tensorflow-avx2:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.0                    py36_0  
astor                     0.7.1                    py36_0  
bzip2                     1.0.6                        17    intel
c-ares                    1.15.0               h7b6447c_1  
certifi                   2018.1.18                py36_2    intel
gast                      0.2.2                    py36_0  
grpcio                    1.14.1           py36h9ba97e2_0  
icc_rt                    2019.3                intel_199    intel
intel-openmp              2019.3                intel_199    intel
intelpython               2019.3                        0    intel
libgcc-ng                 8.2.0                hdf63c60_1  
libprotobuf               3.6.1                hd408876_0  
libstdcxx-ng              8.2.0                hdf63c60_1  
markdown                  3.0.1                    py36_0  
mkl                       2019.3                intel_199    intel
mkl_fft                   1.0.2               np114py36_6    intel
mkl_random                1.0.1               np114py36_6    intel
numpy                     1.14.3                   py36_5    intel
openssl                   1.0.2r                        0    intel
pip                       10.0.1                   py36_0    intel
protobuf                  3.6.1            py36he6710b0_0  
python                    3.6.8                         6    intel
setuptools                39.0.1                   py36_0    intel
six                       1.11.0                   py36_3    intel
sqlite                    3.27.2                        2    intel
tbb                       2019.4                intel_199    intel
tbb4py                    2019.4             py36_intel_0    intel
tcl                       8.6.4                        22    intel
tensorboard               1.10.0           py36hf484d3e_0  
tensorflow-avx2           1.10.0                   py36_0    intel
termcolor                 1.1.0                    py36_1  
tk                        8.6.4                        28    intel
werkzeug                  0.14.1                   py36_0    intel
wheel                     0.31.0                   py36_3    intel
xz                        5.2.3                         2    intel
zlib                      1.2.11                        5    intel
```

conda version 4.6.12 for completeness:

```
$ conda --version
conda 4.6.12
```

**Comment by drj11** [comment]
In this case the problem seems to be that the compilation of tensorflow has bound it to a particular version of glibc (`GLIBC_2.23`). That version of glibc isn't available on ShARC, because only an older version is provided by the OS.

On my laptop, which is running Ubuntu 16.04.5 LTS, `tensorflow-avx2` seems to work (or at least, I can run `python -c 'import tensorflow;tensorflow.Session()'` without getting a similar warning.
